---
controller_manager:
  ros__parameters:
    update_rate: 250        # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50.0

vel_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - right_hip_revolute_joint
      - right_knee_revolute_joint
      - right_ankle_revolute_joint
      - left_hip_revolute_joint
      - left_knee_revolute_joint
      - left_ankle_revolute_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

    constraints:
      goal_time: 0.2
      stopped_velocity_tolerance: 0.1
